In [6]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print("arr1 + arr2 = ", arr1 + arr2)

arr1 + arr2 =  [ 7  9 11 13 15]


In [5]:
print(arr1.shape)

(5,)


In [7]:
arr2.reshape(1, 5)

array([[ 6,  7,  8,  9, 10]])

In [8]:
arr1.reshape(5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
arr1.dot(arr2)

130

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

SQL and SQLite

In [2]:
import sqlite3

In [3]:
connection = sqlite3.connect("test.db")
connection

In [4]:
cursor = connection.cursor()

In [5]:
## create a table
cursor.execute('''
    Create Table if Not Exists employees(
        id Integer Primary Key,
        name Text Not Null,
        age Integer,
        department Text
    )
''')

## Commiting the changes
connection.commit()

In [7]:
cursor.execute('''
    Select * from employees
''')


In [8]:
## Insert the data in sqlite table
cursor.execute('''
    Insert into employees (name, age, department) values ('John', 25, 'HR')
''')

In [9]:
cursor.execute('''
    Insert into employees (name, age, department) values ('Krish', 32, 'Data Scientist')
''')

cursor.execute('''
    Insert into employees (name, age, department) values ('Karan', 22, 'SDE')
''')

cursor.execute('''
    Insert into employees (name, age, department) values ('Oggy', 100, 'Entertainer')
''')

connection.commit()


In [10]:
# Query the Data from the table
cursor.execute('''
               Select * from employees
''')
rows = cursor.fetchall()

## Print the Queried Data

for row in rows:
    print(row)

(1, 'John', 25, 'HR')
(2, 'Krish', 32, 'Data Scientist')
(3, 'Karan', 22, 'SDE')
(4, 'Oggy', 100, 'Entertainer')


In [11]:
## Update the data in the table
cursor.execute('''
    Update employees set age = 26 where name = 'John'
''')


In [12]:
connection.commit()

In [13]:
## Delete the data from the table
cursor.execute('''
    Delete from employees where name = 'John'
''')

connection.commit()

In [17]:
cursor.execute('''
    Select * from employees
''')
rows = cursor.fetchall()
for row in rows:
    print(row)

(2, 'Krish', 32, 'Data Scientist')
(3, 'Karan', 22, 'SDE')
(4, 'Oggy', 100, 'Entertainer')


In [19]:
## Working with sales datw

## Connect to an SQLite database

connection = sqlite3.connect('sales_data.db')
cursor = connection.cursor()

## Create table for sales data
cursor.execute('''
    CREATE TABLE IF NOT EXISTS sales (
        id INTEGER PRIMARY KEY,
        data text not null,
        product text not null,
        sales integer,
        region text
    )
''')

sales_data = [
    ('2021-01-01', 'Laptop', 1000, 'North'),
    ('2021-01-02', 'Laptop', 1500, 'South'),
    ('2021-01-03', 'Desktop', 2000, 'East'),
    ('2021-01-04', 'Desktop', 2500, 'West'),
    ('2021-01-05', 'Desktop', 3000, 'North'),
    ('2021-01-06', 'Laptop', 3500, 'South'),
    ('2021-01-07', 'Laptop', 4000, 'East'),
    ('2021-01-08', 'Desktop', 4500, 'West'),
    ('2021-01-09', 'Desktop', 5000, 'North'),
    ('2021-01-10', 'Laptop', 5500, 'South')
]
cursor.executemany('''
    INSERT INTO sales (data, product, sales, region) VALUES (?, ?, ?, ?)
''', sales_data)

connection.commit()

In [20]:
## Close the connection
connection.close()